### ISSUE TITLE
"Group ON" and "Group OFF" commands are reversed

### ISSUE THREAD

**Issue by gpeltier** [jcrona/rf-ctrl#1]
Suggestion: in `rf-ctrl.c` change

`char *(rf_command_str[]) = {"OFF", "ON", "Group ON",	"Group OFF", "Prog", "F1", "F2", "F3"};`
`char *(rf_cmdline_command_str[]) = { "off", "on", "gon", "goff", "prog", "f1", "f2", "f3"};`

to:

`char *(rf_command_str[]) = {"OFF", "ON", "Group OFF", "Group ON", "Prog", "F1", "F2", "F3"};`
`char *(rf_cmdline_command_str[]) = { "off", "on", "goff", "gon", "prog", "f1", "f2", "f3"};`

**Comment by jcrona** [comment]
Good catch !

**Comment by gpeltier** [comment]
Thanks a lot !
By the way, this is a nice projec t!
